### PR TITLE
Mutex the workers, to behave more like native jest test runs

### PR DESCRIPTION
**Pull request by stipsan**
Makes the developer experience a bit nicer, and more like the `jest-runner` itself: https://github.com/facebook/jest/blob/e566a8f4106ac25b008744ffc42204554fd31cf6/packages/jest-runner/src/index.js#L104-L124

Here's an before/after using jest-runner-prettier on the jest repo itself using these settings:
```js
module.exports = {
  displayName: 'Prettier',
  runner: 'jest-runner-prettier',
  moduleFileExtensions: ['md'],
  testMatch: [
    '**/*.md',
  ],
};
```
Before:
kapture 2018-03-20 at 22 43 54

After:
kapture 2018-03-20 at 22 46 03

Love this library btw 🎉  Great stuff 😄

### CODE REVIEW

**Comment by SimenB** [comment]
Woo! This is great.

Note that #1 removes the `throat` dep, so you might want to re-add it if it's merged before this

**Comment by stipsan** [comment]
Thanks for the heads up, I'll keep an eye out for it 😄

**Comment by keplersj** [comment]
I love that you used `jest-runner-prettier` for this. 😍

**Comment by skratchdot** [comment]
@rogeliog - Any thoughts on this PR?  I just recently started using your lib, but was looking for ways to make my custom runner output look a little more like the other runners I've used (less data in my scrollback history).  This PR seems like it might do it.

**Comment by rogeliog** [comment]
I just published `0.3.0` with this

**Comment by stipsan** [comment]
@rogeliog great, thanks!!

**Comment by skratchdot** [comment]
Nice work @rogeliog / @stipsan !! Trying this out now. Thanks!

**Pull request merged**
