### PR TITLE
Expose ability to skip tests

### PR DESCRIPTION
**Pull request by lgandecki**

### CODE REVIEW

**Comment by keplersj** [comment]
@rogeliog Can we get this merged in? Looks like awesome functionality that would be really helpful in my test runners.

**Comment by rogeliog** [comment]
Yep!

**Comment by rogeliog** [comment]
I just published it as a pre-minor (@0.2.0-0 and @next) I'll promote it to minor soon... let me know if it is all good on your side

**Comment by keplersj** [comment]
@lgandecki You've already been running this in a published fork, right? Good to go?

**Comment by lgandecki** [comment]
Yup, needed it for https://github.com/TheBrainFamily/jest-runner-standard/ . I will be happy to replace the dependency with this original package :)

**Comment by rogeliog** [comment]
Just released 0.2.0

**Pull request merged**
